name: Publish notes
on:
  pull_request:
    branches:
      - v4
  push:
    branches:
      - v4
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8e782a355544971b192db9e75d789dca
          projectName: 9knotes
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: v4
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 This branch can be previewed at ${{ steps.cloudflare-publish.outputs.url }}